# From https://marcus.se.net/obsidian-plugin-docs/publishing/release-your-plugin-with-github-actions

name: Release Obsidian plugin
permissions:
  contents: write

on:
  push:
    tags:
      - "*"

env:
  PLUGIN_NAME: obsidian-typewriter-mode

jobs:
  check:
    uses: ./.github/workflows/check.yml

  build:
    runs-on: ubuntu-latest
    needs: check

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: 'true'
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - uses: extractions/setup-just@v4

      - name: Install grass from crates.io
        uses: baptiste0928/cargo-install@v3
        with:
          crate: grass

      - name: Build
        run: |
          bun install
          just ci
          mkdir ${{ env.PLUGIN_NAME }}
          cp -r dist/* ${{ env.PLUGIN_NAME }}
          zip -r ${{ env.PLUGIN_NAME }}.zip ${{ env.PLUGIN_NAME }}

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          prerelease: ${{ contains(github.ref, '-') }}
          body_path: ./dist/release-notes.md
          files: |
            ${{ env.PLUGIN_NAME }}.zip
            dist/main.js
            dist/manifest.json
            dist/styles.css

